name: Phoenix V100 Instagrapi Cluster

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  strike:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install instagrapi

      - name: Ignite Instagrapi Strike
        env:
          INSTA_COOKIE: ${{ secrets.INSTA_COOKIE }}
          TARGET_THREAD_ID: ${{ secrets.TARGET_THREAD_ID }}
          TARGET_NAME: ${{ secrets.TARGET_NAME }}
        run: python main.py
